services:
    backend:
        image: main
        build:
            context: .
            dockerfile: Dockerfile
        container_name: hackathon_backend
        ports:
            - "8080:8080"
            