services:
    backend:
        image: main
        build:
            context: .
            dockerfile: Dockerfile
        container_name: hackathon_backend
        ports:
            - "8080:8080"
        environment:
            - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=psb_hackathon;Username=postgres;Password=Crossfire1
            - ASPNETCORE_ENVIRONMENT=Production
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:17.5
        container_name: hackathon_db
        environment:
            - POSTGRES_DB=psb_hackathon
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Crossfire1
        ports:
            - "2345:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data: