services:
    backend:
        image: main
        build:
            context: .
            dockerfile: Dockerfile
        container_name: hackathon_backend
        ports:
            - "8080:8080"
        depends_on:
            - db
    # db:
    #     image: postgres
    #     container_name: hackathon_database
    #     environment:
    #         - POSTGRES_DB=HAHATHON
    #         - POSTGRES_USER=admin
    #         - POSTGRES_PASSWORD=Tandem_2025
    #     ports:
    #         - "5432:5432"  