services:
    main_app:
        image: main
        build:
            context: .
            dockerfile: Dockerfile
        container_name: hackathon_app
        ports:
            - "8080:8080"
        depends_on:
            - db



    db:
        image: postgres:latest
        container_name: hackathon_app_db
        environment:
            - POSTGRES_DB=HAHATHON    
            - POSTGRES_USER=admin   
            - POSTGRES_PASSWORD=Tandem_2025
        ports: 
            - "5432:5432"